version: '2'
services:
    loukyainc-app:
        image: loukyainc
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://loukyainc-postgresql:5432/loukyaInc
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    loukyainc-postgresql:
        extends:
            file: postgresql.yml
            service: loukyainc-postgresql
